---
spring:
  cloud:
    config:
      server:
        git:
          uri:  https://khurramsyed@bitbucket.org/khurramsyed/leanmentors.git
          searchPaths:  leanmentors-config
          username:  khurramsyed
          password:  Highhopes2