---
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8010/eureka/

---
spring:
 profile: primary
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8011,http://localhost:8012


---
spring:
 profile: secondary
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8010,http://localhost:8012

---
spring:
 profile: tertiary
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8010,http://localhost:8011

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog 
